### ISSUE TITLE
Corruption still crashes arena

### ISSUE THREAD

**Issue by DryCryCrystal** [DryCryCrystal/Region-Kit#44]
A user was having issues with arena and corruption
[consoleLog (25).txt](https://github.com/DryCryCrystal/Region-Kit/files/8056804/consoleLog.25.txt)
[exceptionLog (72).txt](https://github.com/DryCryCrystal/Region-Kit/files/8056805/exceptionLog.72.txt)

**Comment by M4rbleL1ne** [comment]
Works for 2 other people.

**Comment by M4rbleL1ne** [comment]
ConfigMachine crashed or smth

**Comment by DryCryCrystal** [comment]
Mods incorrectly installed, no issue with region kit
